project_id = "dsmahpgrhjoikcxuiqrw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[[api.jwt.claims]]
key = "role"
value = "authenticated"

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true