project_id = "dsmahpgrhjoikcxuiqrw"

[global.env]
RESEND_API_KEY = "re_"

[[functions]]
name = "send-temp-password-email"
verify_jwt = false

[[functions]]
name = "send-client-activation-emails"
verify_jwt = false