project_id = "dsmahpgrhjoikcxuiqrw"

[[functions]]
name = "send-temp-password-email"
verify_jwt = false

[[functions]]
name = "send-client-activation-emails"
verify_jwt = false

[[functions]]
name = "send-activation-email"
verify_jwt = false